
import data from '../../data/usStatesCities.json';
const CountryList = [
  "United States",
  "United Arab Emirates",
  "Malaysia",
  "Saudi Arabia",
  "Myanmar",
  "United Kingdom",
  "South Africa",
  "Canada",
  "Sri Lanka",
  "Kuwait",
  "Oman",
  "Singapore",
  "Qatar",
  "Nepal",
  "Australia",
  "Mauritius",
  "Trinidad and Tobago",
  "Fiji",
  "New Zealand",
  "Bahrain",
];



const CountryStateList = [
  {
    country: "United States",
    states: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
  },
  {
    country: "United Arab Emirates",
    states: [
      "Abu Dhabi",
      "Ajman",
      "Dubai",
      "Fujairah",
      "Ras Al Khaimah",
      "Sharjah",
      "Umm Al Quwain",
    ],
  },
  {
    country: "Malaysia",
    states: [
      "Johor",
      "Kedah",
      "Kelantan",
      "Malacca",
      "Negeri Sembilan",
      "Pahang",
      "Penang",
      "Perak",
      "Perlis",
      "Sabah",
      "Sarawak",
      "Selangor",
      "Terengganu",
    ],
  },
  {
    country: "Saudi Arabia",
    states: [
      "Riyadh",
      "Makkah",
      "Madinah",
      "Eastern Province",
      "Asir",
      "Tabuk",
      "Al Qassim",
      "Hail",
      "Jazan",
      "Najran",
      "Al Bahah",
      "Al Jawf",
      "Northern Borders",
    ],
  },
  {
    country: "Myanmar",
    states: ["Kachin", "Kayah", "Kayin", "Chin", "Mon", "Rakhine", "Shan"],
  },
  {
    country: "United Kingdom",
    states: ["England", "Scotland", "Wales", "Northern Ireland"],
  },
  {
    country: "South Africa",
    states: [
      "Eastern Cape",
      "Free State",
      "Gauteng",
      "KwaZulu-Natal",
      "Limpopo",
      "Mpumalanga",
      "Northern Cape",
      "North West",
      "Western Cape",
    ],
  },
  {
    country: "Canada",
    states: [
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Nova Scotia",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Northwest Territories",
      "Nunavut",
      "Yukon",
    ],
  },
  {
    country: "Sri Lanka",
    states: [
      "Central",
      "Eastern",
      "Northern",
      "North Central",
      "North Western",
      "Sabaragamuwa",
      "Southern",
      "Uva",
      "Western",
    ],
  },
  {
    country: "Kuwait",
    states: [
      "Al Ahmadi",
      "Al Asimah",
      "Al Farwaniyah",
      "Al Jahra",
      "Hawalli",
      "Mubarak Al-Kabeer",
    ],
  },
  {
    country: "Oman",
    states: [
      "Ad Dakhiliyah",
      "Ad Dhahirah",
      "Al Batinah North",
      "Al Batinah South",
      "Al Buraimi",
      "Al Wusta",
      "Dhofar",
      "Musandam",
      "Muscat",
      "North Al Sharqiyah",
      "South Al Sharqiyah",
    ],
  },
  {
    country: "Singapore",
    states: [],
  },
  {
    country: "Qatar",
    states: [
      "Ad Dawhah",
      "Al Daayen",
      "Al Khor",
      "Al Rayyan",
      "Al Shamal",
      "Al Wakrah",
      "Umm Salal",
      "Madinat ash Shamal",
    ],
  },
  {
    country: "Nepal",
    states: [
      "Koshi",
      "Madhesh",
      "Bagmati",
      "Gandaki",
      "Lumbini",
      "Karnali",
      "Sudurpashchim",
    ],
  },
  {
    country: "Australia",
    states: [
      "New South Wales",
      "Queensland",
      "South Australia",
      "Tasmania",
      "Victoria",
      "Western Australia",
      "Australian Capital Territory",
      "Northern Territory",
    ],
  },
  {
    country: "Mauritius",
    states: [
      "Black River",
      "Flacq",
      "Grand Port",
      "Moka",
      "Pamplemousses",
      "Plaines Wilhems",
      "Port Louis",
      "Rivière du Rempart",
      "Savanne",
      "Rodrigues",
    ],
  },
  {
    country: "Trinidad and Tobago",
    states: [
      "Arima",
      "Chaguanas",
      "Couva-Tabaquite-Talparo",
      "Diego Martin",
      "Mayaro-Rio Claro",
      "Penal-Debe",
      "Point Fortin",
      "Port of Spain",
      "Princes Town",
      "San Fernando",
      "San Juan-Laventille",
      "Sangre Grande",
      "Siparia",
      "Tobago",
    ],
  },
  {
    country: "Fiji",
    states: ["Central", "Eastern", "Northern", "Western"],
  },
  {
    country: "New Zealand",
    states: [
      "Northland",
      "Auckland",
      "Waikato",
      "Bay of Plenty",
      "Gisborne",
      "Hawke's Bay",
      "Taranaki",
      "Manawatū-Whanganui",
      "Wellington",
      "Tasman",
      "Nelson",
      "Marlborough",
      "West Coast",
      "Canterbury",
      "Otago",
      "Southland",
    ],
  },
  {
    country: "Bahrain",
    states: ["Capital", "Muharraq", "Northern", "Southern"],
  },
];

const DropDownList = () => {
    let newCountryStateList = [];
    for(let i = 0; i<CountryList.length; i++){
        let country = CountryList[i];
        for(let j = 0; j<CountryStateList.length; j++){
            if(country === CountryStateList[j].country){
                let str = country.replace(/ /g, "").toLowerCase();
                newCountryStateList.push({ [str]: CountryStateList[j].states });
                break;
            }
        }
    }

    

    return newCountryStateList;
}

export default DropDownList;

